services:
  milvus_etcd:
    hostname: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
      - NO_PROXY=localhost,milvus_standalone,minio
      - no_proxy=localhost,milvus_standalone,minio
      - HTTPS_PROXY=
      - HTTP_PROXY=
      - https_proxy=
      - http_proxy=
    volumes:
      - ./.data/etcd:/etcd
    command: etcd -advertise-client-urls=http://localhost:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - arxivrag_network


  milvus_standalone:
    hostname: milvus-standalone
    image: milvusdb/milvus:v2.3.20
    command: ["milvus", "run", "standalone"]
    security_opt:
    - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: milvus_etcd:2379
      MINIO_ADDRESS: minio:9000
      NO_PROXY: localhost,milvus_etcd,minio,172.21.6.0/24
      no_proxy: localhost,mulvus_etcd,minio,172.21.6.0/24
      HTTPS_PROXY: 
      HTTP_PROXY: 
      https_proxy: 
      http_proxy: 
    volumes:
      - ./.data/milvus:/var/lib/milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 10s
      start_period: 10s
      timeout: 10s
      retries: 3
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      milvus_etcd:
        condition: service_healthy
    networks:
      - arxivrag_network

networks:
  arxivrag_network:
    name: arxivrag_network
    external: true